// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'member.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Member _$MemberFromJson(Map<String, dynamic> json) => Member(
      json['mb_id'] as String,
      json['mb_name'] as String,
      json['mb_auth'] as String,
      json['mb_nick'] as String,
      json['mb_email'] as String,
      json['mb_level'] as String,
      json['mb_sex'] as String,
      json['mb_birth'] as String,
      json['mb_tel'] as String,
      json['mb_hp'] as String,
      json['mb_fax'] as String,
      json['mb_zip'] as String,
      json['mb_addr1'] as String,
      json['mb_addr2'] as String,
      json['mb_addr3'] as String,
      json['mb_addr_jibeon'] as String,
      json['mb_point'] as String,
      json['mb_money'] as String,
      json['mb_today_login'] as String,
      json['mb_login_ip'] as String,
      json['mb_datetime'] as String,
      json['mb_ip'] as String,
      json['mb_leave_date'] as String,
      json['mb_intercept_date'] as String,
      json['mb_mailling'] as String,
      json['mb_sms'] as String,
      json['mb_open'] as String,
      json['mb_open_date'] as String,
      json['mb_img'] as String,
      json['mb_block'] as String,
      json['mb_singo'] as String,
      json['mb_app'] as String,
      json['gr_id'] as String,
      json['gr_subject'] as String,
      json['gr_type'] as String,
      json['gr_regis_use'] as String,
      json['gr_auth_use'] as String,
      json['me_loc'] as String,
      json['ar_gugun'] as String,
      json['total_money'] as int,
    );

Map<String, dynamic> _$MemberToJson(Member instance) => <String, dynamic>{
      'mb_id': instance.mb_id,
      'mb_name': instance.mb_name,
      'mb_auth': instance.mb_auth,
      'mb_nick': instance.mb_nick,
      'mb_email': instance.mb_email,
      'mb_level': instance.mb_level,
      'mb_sex': instance.mb_sex,
      'mb_birth': instance.mb_birth,
      'mb_tel': instance.mb_tel,
      'mb_hp': instance.mb_hp,
      'mb_fax': instance.mb_fax,
      'mb_zip': instance.mb_zip,
      'mb_addr1': instance.mb_addr1,
      'mb_addr2': instance.mb_addr2,
      'mb_addr3': instance.mb_addr3,
      'mb_addr_jibeon': instance.mb_addr_jibeon,
      'mb_point': instance.mb_point,
      'mb_money': instance.mb_money,
      'mb_today_login': instance.mb_today_login,
      'mb_login_ip': instance.mb_login_ip,
      'mb_datetime': instance.mb_datetime,
      'mb_ip': instance.mb_ip,
      'mb_leave_date': instance.mb_leave_date,
      'mb_intercept_date': instance.mb_intercept_date,
      'mb_mailling': instance.mb_mailling,
      'mb_sms': instance.mb_sms,
      'mb_open': instance.mb_open,
      'mb_open_date': instance.mb_open_date,
      'mb_img': instance.mb_img,
      'mb_block': instance.mb_block,
      'mb_singo': instance.mb_singo,
      'mb_app': instance.mb_app,
      'gr_id': instance.gr_id,
      'gr_subject': instance.gr_subject,
      'gr_type': instance.gr_type,
      'gr_regis_use': instance.gr_regis_use,
      'gr_auth_use': instance.gr_auth_use,
      'me_loc': instance.me_loc,
      'ar_gugun': instance.ar_gugun,
      'total_money': instance.total_money,
    };
